### ISSUE TITLE
关于分词

### ISSUE THREAD

**Issue by CaoDongDong1991** [wuYinBest/bilibili-live-crawler#4]
你好
首先感谢你的知识分享
最近我需要使用上分词处理，我在使用你的demo的时候，发现一般需要3秒左右
请问有什么更好的方案推荐的么？

**Comment by wuYin** [comment]
这是 PHP 实现的简洁版 [结巴分词](https://github.com/fxsjy/jieba)，除了优化代码，在语言层面还可以选择其他实现，参考：["结巴"(Jieba)中文分词系列性能评测](https://yanyiwu.com/work/2015/06/14/jieba-series-performance-test.html)，直接使用 C++ 或 Golang 实现的库应该能达到你的要求

**Comment by CaoDongDong1991** [comment]
thank you sir.
